name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  asdf:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14 # M1
          - macos-13 # Intel
        target:
          - tool-version: 'latest'
            command: 'yamlfmt -help'
          - tool-version: '0.1.0'
            # makers does not exist
            command: 'yamlfmt -help'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v3
        with:
          version: ${{ matrix.target.tool-version }}
          command: ${{ matrix.target.command }}

  mise:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        target:
          - command: 'mise x yamlfmt@latest -- yamlfmt -help'
          - command: 'mise x yamlfmt@0.1.0 -- yamlfmt -help'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          tool_versions: |
            # Should not set yamlfmt versions here. (Actually shellcheck is not used here)
            shellcheck 0.9.0
      - name: Setup mise
        run: |
          mise plugins install yamlfmt https://github.com/kachick/asdf-yamlfmt.git#${{ github.ref }}
      - name: Test
        run: |
          ${{ matrix.target.command }}
