name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      - run: 'asdf plugin-add yamlfmt .'
      - uses: asdf-vm/actions/install@v3
      - run: scripts/lint.bash
