name: Release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          min-interval-seconds: 5
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
